export const GET_CARD_LOADING = 'GET_CARD_LOADING';
export const GET_CARD_SUCCESS = 'GET_CARD_SUCCESS';
export const GET_CARD_FAILURE = 'GET_CARD_FAILURE';

export const EDIT_CARD_LOADING = 'EDIT_CARD_LOADING';
export const EDIT_CARD_SUCCESS = 'GET_CARD_SUCCESS';
export const EDIT_CARD_FAILURE = 'EDIT_CARD_FAILURE';
